name: Continuous Delivery of llvm-firtool

on:
  # TODO delete, this should only be workflow_dispatch and cron
  pull_request:
  workflow_dispatch:
  # Run every 8 hours to balance compute with picking up new releases of llvm/circt
  schedule:
    - cron: '0 */8 * * *'


jobs:
  detect:
    name: Detect New Versions
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@v1
      - id: detect-versions
        run: |
          scala-cli .github/scripts/FindNewReleases.scala -- versions.json
          versions=$(cat versions.json)
          echo "versions=$versions" >> $GITHUB_OUTPUT
    outputs:
      versions: ${{ steps.detect-versions.outputs.versions }}

  publish:
    name: Publish LLVM Firtool
    needs: detect
    strategy:
      matrix:
        version: ${{ fromJSON(needs.detect.outputs.versions) }}
    uses: ./.github/workflows/publish-llvm-firtool.yml
    with:
      version: ${{ matrix.version }}
      snapshot: false
    secrets: inherit
