name: Continuous Delivery of llvm-firtool

on:
  workflow_dispatch:
  # Run every 15 min, checking for new releases is cheap.
  schedule:
    - cron: '*/15 * * * *'


jobs:
  detect:
    name: Detect New Versions
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        run: echo "JAVA_HOME=${JAVA_HOME_17_X64}" >> "$GITHUB_ENV"
      - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@v1
        with:
          jvm: '' # Deliberately empty to avoid downloading JVM.
      - id: detect-versions
        run: |
          # --server=false avoids an hang.
          versions=$(scala-cli --server=false .github/scripts/FindNewReleases.scala)
          echo "versions=$versions" >> $GITHUB_OUTPUT
    outputs:
      versions: ${{ steps.detect-versions.outputs.versions }}

  publish:
    name: Publish LLVM Firtool
    needs: detect
    if: ${{ needs.detect.outputs.versions != '[]' }}
    strategy:
      matrix:
        version: ${{ fromJSON(needs.detect.outputs.versions) }}
    uses: ./.github/workflows/publish-llvm-firtool.yml
    with:
      version: ${{ matrix.version }}
      snapshot: false
    secrets: inherit
