name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    name: Run Tests
    uses: ./.github/workflows/test.yml
    with:
      version: '1.58.0'
      snapshot: 'true'
